services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - .env
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    command: start-dev --http-enabled=true

  mailserver:
    image: 'mailserver/docker-mailserver:latest'
    hostname: mail.local
    domainname: local
    env_file:
      - .env
    ports:
      - '25:25'
      - '143:143'
      - '587:587'
      - '993:993'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8888:8888'
    depends_on:
      - postgres
      - redis
      - keycloak
#    volumes:
#      - .:/app
#    command: python manage.py runserver
