spring:
  profiles:
    active: production
  application:
    name: ecom
  config:
    import: file:src/main/resources/db.yml, file:src/main/resources/media.properties, optional:file:src/main/resources/security.yml, file:src/main/resources/viettel-payment.yml, file:src/main/resources/mail.yml
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8888
  servlet:
    context-path: /api